### ISSUE TITLE
[3] Create reports infrastructure

### ISSUE THREAD

**Issue by alexeykuzmin0** [alexeykuzmin0/ThePlatform#17]
1. Create an interface of IReport
2. Create two classes implementing this interface: ProfitReport and DefaultStatisticsReport
3. Extend an existing BackTester to report results in the form of Report requested

**Comment by alexeykuzmin0** [comment]
Satistics for pt.2:
1. Profit.
2. Drawdown.
3. Profit / drawdown.
4. Number of trades.
5. Profit / trade.
6. Number + trades.
7. Share of + trades.
8. Profit of + trades.
9. Profit / trade for + trades.
10. Number - trades.
11. Share of - trades.
12. Loss of - trades.
13. Loss / trade for - trades..
14. Max strike of + trades.
15. Max strike of - trades.
16. Max recovery time.

**Comment by stasvr** [comment]
Think we can add some more parametrs such ass:
1. Expected value on specified time band (>> Moving Average)
2. Dispersion for expected value

**Comment by alexeykuzmin0** [comment]
Discussed on-site: all new statistics wil be added as new issues in future

**Comment by alexstr22** [comment]
Tested, no comments found
