### ISSUE TITLE
[1] Improve datetime type usability

### ISSUE THREAD

**Issue by stasvr** [alexeykuzmin0/ThePlatform#7]
Have some problems with converting it to string, time_t, tm(which can be realy helpfull, because its structure) or another types...

**Comment by alexeykuzmin0** [comment]
The type should be convertible to std::string. Any other useful improvements are appreciated

**Comment by stasvr** [comment]
i mean it would be nice if we could take the fields which we want take frome datetime

**Comment by alexeykuzmin0** [comment]
Closing as won't fix: unclear why we need these features.
